image: python:3.13.3-alpine3.20

before_script:
  - python3 -m venv .venv 
  - . .venv/bin/activate
  - pip install -r requirements-dev.txt

stages:
  - style
  - docs
  - test

pylint:
  stage: style
  script:
  - python -m pylint --rcfile=.pylintrc --fail-under=6 --ignore-paths="migrations/*" config/ main/
  - echo "Pylint complete."
  artifacts:
    when: on_success
    expire_in: 30 days

pycodestyle:
  stage: style
  script:
  - python -m pycodestyle config/ main/ --config=setup.cfg --count
  - echo "Pycodestyle complete."
  artifacts:
    when: on_failure
    expire_in: 30 days
  allow_failure: true

tests:
  stage: test
  script:
  - python -m pytest main/tests/ -v --cov=main --cov-report=term --cov-report=html
  - echo "Tests complete."
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - htmlcov/
  allow_failure: false

sphinx_docs:
  stage: docs
  script:
  - pip install -r docs/requirements.txt
  - sphinx-build -b html docs docs/_build/html
  - echo "Documentation build complete."
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - docs/_build/
  allow_failure: true