# Generated by Django 6.0.4 on 2026-05-07 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_complaint_is_resolved_complaint_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='target_type',
            field=models.CharField(choices=[('question', 'Вопрос'), ('answer', 'Ответ'), ('user', 'Пользователь')], default='question', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('spam', 'Спам'), ('offensive', 'Оскорбление'), ('incorrect', 'Неверная информация'), ('user_behavior', 'Плохое поведение пользователя'), ('other', 'Другое')], max_length=20),
        ),
    ]
