# Generated by Django 4.2.28 on 2026-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint_target_type_complaint_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
